name: release

on: workflow_dispatch

jobs:
  publish:
    inputs:
      packageToPublish:
        description: 'Package to publish'
        required: true
        default: '.'
        type: choice
        options:
          - .
          - ./packages/date
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm
          registry-url: https://registry.npmjs.org
          always-auth: true

      - run: cd ${{ github.event.inputs.packageToPublish }} && npm install

      - run: cd ${{ github.event.inputs.packageToPublish }} && npm run test

      - run: cd ${{ github.event.inputs.packageToPublish }} && npm run build

      - name: Publish to NPM
        if: ${{ github.ref == 'refs/heads/main' }}
        run: cd ${{ github.event.inputs.packageToPublish }} && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
