name: Tests

on:
  push:
    paths-ignore:
      - ".md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [chrome, firefox, edge]
    name: test ${{ matrix.runtime }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm run test
        env:
          TEST_RUNTIME: ${{ matrix.runtime }}
  node:
    runs-on: ubuntu-latest
    name: test node v20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm run test -- --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  bun:
    runs-on: ubuntu-latest
    name: test bun
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun --bun run build
      - run: bun test
  node-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23, 22, 20, 18]
    name: test node v${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: npm run test
